# Generated by Django 4.2.23 on 2025-07-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"verbose_name": "Бренд", "verbose_name_plural": "Бренди"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукти"},
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата створення"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Meta Description"
            ),
        ),
    ]
